### ISSUE TITLE
Review Schematics + Layout

### ISSUE THREAD

**Issue by Informaticore** [sethkaz/SuperPower#4]
Review of the RPi Schematics + Layout by Mirko

1. Pi-Input-Source.sch: USB-C Shield is connected to ground. For some reason I can not remember but I think someone said it could lead to issues, the ESP Board has it not connected to GND. We placed a 0R Resistor (DNP) just in case but it sais that the Shield should be floating on the device side. 

2. On the layout I see solid areas - which I like - but they have pretty weird shapes which would look weird on the board. Just a optical thing, I would make them more straight and nicely shaped. 
3. Missing bunch of 3D Objects which should be added
4. I would also remove the 3D file for the components which are not populated
5. No meaningfull silk-screen. Are there any plans of putting some details on the silk? I also placed the designators inside the component boarders and made them invisble on the silk-layer but for a prototype it makes sens to have them. The designator inside the border helps the assembly to see where which component is placed as well. but thats not a must.

**Comment by sethkaz** [comment]
Responses:

1. That's a good idea. I would prefer having the shield connected to ground, but having an easy method for disconnecting would be useful. I'll add a shorted jumper.

2. The planes definitely do have odd shapes.  There are a few reasons for this, and I'm not sure if it's truly fixable.  We are sticking to a 2 layer board, so the routing at the non-GND power planes all have to share a layer.  This forces us to work around the components that have fixed or relatively fixed locations.  Also, I used the plane boundaries to limit the shapes of the planes rather than allow the CAD to fill the plane as far as it could.  The latter could result in copper in odd places and in worse shapes, which could result in unintentional antennas being created.

3/4. This is a known shortcoming.  The 3d models are not needed for fab and assembly, and will be fixed soon.

5. Yes, that should be done.  At the very least, add some name and version indicators.  Regarding the Reference Designators being inside the components and therefore being not visible in the final assembly, I would disagree with this.  We are making an open-source design for others to use and study.  Having the RefDes visible on the board makes it easier for them to investigate and poke around.  The only time that having RefDes not visible on a PCB is when there truly is absolutely no room to put them.
